### ISSUE TITLE
Syntax specification of the match target? 

### ISSUE THREAD

**Issue by thautwarm** [gvanrossum/patma#102]
So far in PEP we see a grammar:

```
match_stmt: "match" expression ':' NEWLINE INDENT case_block+ DEDENT
```

This rejects following code:

```python
match 1, 2:
    case 1, 2:
       ...
```

While `case` accepts a comma-separated expression list.

Is the grammar of `match_stmt` intentional?

**Comment by brandtbucher** [comment]
Yeah, this should probably be `star_expressions` to allow the unparenthesized tuple. If @gvanrossum agrees I'll update the PEP and implementation.

Did we agree to explicitly disallow named expressions here, or was that an oversight?

**Comment by gvanrossum** [comment]
I don’t think we gave it much thought. Star-expression seems right. (Does that include await? It should.) Be sure to update the Appendix. (In the main body of the PEP this detail is a distraction.)

**Comment by lysnikolaou** [comment]
> Does that include await?

It does.

**Comment by brandtbucher** [comment]
By the way, congrats on your promotion @lysnikolaou!

**Comment by lysnikolaou** [comment]
Thanks a bunch, @brandtbucher! 🎉

**Comment by gvanrossum** [comment]
Since this a minor detail I’m closing it.
