### ISSUE TITLE
Idea for matching bytes

### ISSUE THREAD

**Issue by gvanrossum** [gvanrossum/patma#103]
In a long ramble by Rhodri James I found this idea with some merit:
```
    match msg:
     case bytes((len, 0, cmd, *rest)):
       process_command[cmd](len, rest)
     case bytes((len1, len2, 0, cmd, *rest)) if len1 >= 0x80:
       process_command[cmd]((len1 & 0x7f) | (len2 << 7), rest)
     else:
       handle_comms_error(msg)
```
Maybe we could make this work with an appropriate `bytes.__match__` method? Though what would probably exclude also accepting `case bytes(b"abc")`.

Thoughts?

**Comment by brandtbucher** [comment]
It would just have to return a non-`bytes` `Sequence` as its proxy, right? Perhaps we could do something similar for `str`/`bytearray`?

It only makes sense if it outweighs `case bytes(b"something")`. But I think it does, and this shouldn't be hard.

**Comment by thautwarm** [comment]
`[len1, len2, cmd, *rest]` cannot match `b"abcd"? Isn't a `bytes` a `Sequence`?

**Comment by brandtbucher** [comment]
Please read the PEP. We exclude `str`, `bytes`, and `bytearray` from this rule.

But this is an elegant way of saying "I know what I'm doing, just treat is like a sequence.". Bonus points for these types not having any static attributes anybody would want to pull off of the proxy.

**Comment by brandtbucher** [comment]
```py
class bytes:
    @classmethod
    def __match__(cls, target):
        if isinstance(target, cls):
            return tuple(target)

class bytearray:
    @classmethod
    def __match__(cls, target):
        if isinstance(target, cls):
            return tuple(target)

class str:
    @classmethod
    def __match__(cls, target):
        if isinstance(target, cls):
            return tuple(target)
        
```

**Comment by thautwarm** [comment]
If new syntax is okay,
```python
match v:
   case bytes[a, b, c, *d]: ...
```

**Comment by brandtbucher** [comment]
> If new syntax is okay,

Sorry, not really.

**Comment by gvanrossum** [comment]
Hm, if we're really having to unpack the bytes object in the `__match__` method, then we might as well not do it. Rhodri cn just write
```
match list(value):
    case [len, 0, cmd, *rest]:
        ...
    # etc.
```
