### ISSUE TITLE
Should __match_args__ be defined on the match proxy?

### ISSUE THREAD

**Issue by natelust** [gvanrossum/patma#106]
Apologies if this has been addressed, I attempted to read through the issues and I didn't see the answer in the pep. The current specification is that `__match_args__` will be looked up on the class that defines `__match__`. Consider the case where the match proxy that is returned from match does not share any attributes in common with the class that defines match. For instance, the following stub where a str is matched against an object that decides if a string is a valid url (only one match case for the str is shown, other cases are not important for this example).

```python
class URLStringMatcher:
    _matcher = r"(?i)\b((https://|[a-z0-9.\-]+[.][a-z]{2,4}/)(?:[^\s()<>]+|\(([^\s()<>]+|(\([^\s()<>]+\)))*\))+(?:\(([^\s()<>]+|(\([^\s()<>]+\)))*\)|[^\s`!()\[\]{};:'\".,<>?«»“”‘’]))" 
    @classmethod
    def __match__(obj):
        if not isinstance(obj, str):
            return None
        if re.findall(regex, obj)
            return requests.get(obj)

match 'https://python.org':
    case URLStringMatcher(..., status_code = 200, ..., text, ....):
        print('text')
```
 It would be nice to use the `__match_args__` that are defined on the map proxy (ignore that they are not defined for this object yet) instead of redefining them on the match class. This example is probably not the best way to implement this behavior, but it is just the first example that I thought of.

In the default case where match returns the object itself, `__match_args__` would still be defined on the object itself. This fact may be reason enough to not change where `__match_args__` is defined. Understanding where this attribute should be defined may be more confusing than attributes in the` __match_args__` not existing on the class defining `__match__`.

I was just wondering if this had been discussed.

**Comment by gvanrossum** [comment]
That is a ridiculous use case. Dunder match should do as little work as possible, and definitely no I/O.

Please find the existing issue where we discussed this. There are good reasons.

**Comment by natelust** [comment]
I agree it would be ridiculous to actually do this in practice, it was just an example of using another object that came to mind. I should have taken the time to come up with a proper example of wanting to share a mapping proxy class before commenting. I did try to search issues for this discussion, but clearly failed, I will go back and hunt harder. Im sure you have lots going on now to comment on, sorry for the extra cognitive load.

**Comment by viridia** [comment]
The problem has to do with a `__match__` method that returns the original object - and the object being a subclass of the matched class which overrides `__match_args__`, causing the match to fail because it's mixing two different protocols, one from the pattern and one from the pattern subclass.

**Comment by natelust** [comment]
That makes a lot of sense, thank you for repeating the thinking here. I will try to do  more thorough background reading before submitting future issues.
