### ISSUE TITLE
Wrong statement about Haskell in PEP

### ISSUE THREAD

**Issue by dmoisset** [gvanrossum/patma#107]
The PEP says in https://www.python.org/dev/peps/pep-0622/#id86:

"A technique occasionally seen in functional languages like Haskell is to use a match variable multiple times in the same pattern:" (followed by the `Point(x, x)` example). That's actually wrong, and the Haskell compiler  does not accept a definition like `f a a = a+1`, throwing instead a compile time error.

The normal way of doing this in Haskell is with guards :)

**Comment by gvanrossum** [comment]
Probably one of the other functional languages supports this idiom. Which?

**Comment by thautwarm** [comment]
Erlang
