### ISSUE TITLE
Bug in one of the examples

### ISSUE THREAD

**Issue by dmoisset** [gvanrossum/patma#109]
In https://github.com/gvanrossum/patma/blob/master/EXAMPLES.md#case-5-deep-type-iterable-and-value-matches-with-extraction , the pattern tries to match with `none_rprimitive` (which is a constant), but instead binds that name as a local.

Funny I should come across this while I was slowly convincing myself that store semantics (#90) was the right thing :)

**Comment by brandtbucher** [comment]
Well, if it helps at all, those examples are ancient (before we were even concerning ourselves with load vs store).

That said, they should probably be updated to match (ha) the current spec.

**Comment by dmoisset** [comment]
Oh, I saw a recent commit date and thought they were current. Is there any collection of examples being explored?

**Comment by gvanrossum** [comment]
Examples can serve many purposes. They can be meant to aid basic understanding, or to show edge cases, or to inform the design, or to convince opponents...

We probably need separate sets of examples for each. The EXAMPLES.md file was mostly meant to inform the design. But let’s at least fix it. :-)

**Comment by gvanrossum** [comment]
Fixed in 15b82ab097238dde510e291b447accc979d7ddc6.
