### ISSUE TITLE
(issue withdrawn)

### ISSUE THREAD

**Issue by ambientnuance** [gvanrossum/patma#118]
As the two comments below indicate, this thread was not appropriate for this PEP - so I am withdrawing my comments from this forum.

**Comment by ambientnuance** [comment]
Below is a list of the syntactic choices made. For brevity, I refer to the specification of an object’s structure as a ‘spec’, of which several can be joined by ‘|’ to form a ‘case spec’.
- ‘_’ remains a wildcard. The only extension of its current use as a ‘catch all’ name is to allow its use multiple times within a single spec.
- Store variables have no modifiers (looks like regular unpacking, follows the behaviour of comprehensions and lambda expressions).
- Load variables without dot nesting are designated by a ‘?’ suffix.
- Any dot nested object is treated as a load variable.
- ‘case _: ‘ is the ‘match-any’ clause (consistency with pattern matching, and doesn’t bleed the concept of match/case further into the switch/case space).
- Class-based pattern matching is done via ‘attribute lookup’ using ‘[ ]’ braces. To match an object with such a pattern, it must be an _existing_ instance of the designated class with all attributes matched. The spec for all unspecified attributes is implicitly set to ‘_’.
  - Attribute specs can be constructed the same as any other spec – structural patterns, store and load variables, constants.
  - Using ‘[ ]’ instead of ‘( )’ avoids the conflation with creating a new instance in place.
- Multiple specs within a case statement are separated by ‘|’ rather than ‘or’.
- Literal values can be used in place.
- Specs and case specs can optionally be wrapped in ‘( )’ for visual distinction. Tuple structures must be specified using a comma - ‘(, )’.
- The guard clause must evaluate to a boolean, but can be arbitrarily long.

**Comment by ambientnuance** [comment]
Some choices/proposals that involve the flow of code execution, etc.:
- All match variables are local only to their case block.
- Persistence of a matched value beyond the match block can be done by an in-line assignment to the ‘_’ wildcard. E.g., “case x=_:” reads as: “Load the value matched by the wildcard into the variable x”.
  - Note that such persistence can also be achieved by explicitly assigning a store variable to any variable already defined outside the match block.
- Only one matching case block is executed (reduce confusion for switch/case usage). If this is not a preferred option by some, I can start another issue to flesh out my reasoning.

**Comment by ambientnuance** [comment]
None of the choices above cover the syntax or implementation of __match__() and/or other hidden/duck-typing methods.

**Comment by ambientnuance** [comment]
In regards to the ‘future-proof’ choices for ‘|’ and ‘?’, I am in the process of writing up a brief proposal of ideas to give them an intuitive and consistent meaning as operators, which is extended other special characters. It is definitely outside the scope of this PEP, but demonstrates a meaningful line of development for the use of ‘|’ and ‘?’. To summarise these ideas (very) briefly:
- ‘?’ and ‘!’ → type and not-type aware operators
- ‘|, &, ^, -’ → set operators generalised to tuples, lists, sets and dicts and (most) combinations thereof.

**Comment by ambientnuance** [comment]
Thanks to @brandtbucher for the suggestion to step back and divert my freight train of thought from a single GitHub issue^. Motivated by the relative arbitrarity of the syntax choices for the match/case construct, I tried to reason about syntax and its sugary variants in a general sense. A concept that steered my thinking throughout can be compressed (lossy) into a conditional assignment:
```
syntax = sorted(choices) if user > compiler else garbage
```
In a separate repo, I will be uploading coherent forms of my thought-freight as they are completed.
In my view, any decision regarding the expansion of use for special characters in Python _should_ take time and be done so with deliberate care and consultation. Many people love Python for what it is today (also for what it is not), and the language will still be here well after 3.10. For me, a good outcome for integrating more special characters into the language would be that they are comprehended by all, even if used only by some.
^Yet here I am in a single issue again

**Comment by brandtbucher** [comment]
> Thanks to @brandtbucher for the suggestion to step back and divert my freight train of thought from a single GitHub issue^.

Well actually, from [the repo](https://github.com/gvanrossum/patma/issues/92#issuecomment-650413743).

> ^Yet here I am in a single issue again.

Yet here you are.
