### ISSUE TITLE
Making pattern matching more usable for testing

### ISSUE THREAD

**Issue by dmoisset** [gvanrossum/patma#120]
Context: This is an idea I find attractive but I believe it should NOT be part of the proposal. However if you find it interesting I'd like it to be put in "deferred" ideas, because people could take it as a nice incentive to support the PEP.

While exploring a bit around motivators and applications of pattern matching, I noticed an area that we haven't talked much about where there's a lot of potential: testing. It is not uncommon to test component x by making a call on x and then asserting that the result, instead of being equal to a concrete value, has a certain "shape", which the patterns of the PEP fit really well (I'll add several examples from the stdlib in the comments;  I found many very quickly randomly browsing files).

One annoyance I find to sell this is that the typical usage would be:

```python
match x.method(test_args):
    case <pattern+guard for correct shape>: pass
    case _: assert False, "the result of x.method has the wrong shape"
```

Something that I'd like (again, this is to put as a deferred idea) is some sort of assertion statement to use in this scenario. I'm not sure the specific concrete syntax but in abstract it should be something like `assert <expression> matches <pattern>`. I think this makes many tests much more clear and succinct, and makes for a great application of patterns. And also I'm sure tools like pytest could analyse that more easily to provide great error messages.

How do you feel about this application of patterns?

**Comment by dmoisset** [comment]
Some examples from the stdlib test suit. I've commented out the original code, and added in what the modified code would look like. Note that the modified version would end up having plain assert-like statements (following a pytest-like style, rather than `unittest.assertXyz` style. The `unittest` style would be harder to implement as `assertMatches(obj, pattern)` because our patterns are not first class):

```python
# examples from test_calendar.py

def test_itermonthdays4(self):
    cal = calendar.Calendar(firstweekday=3)
    days = list(cal.itermonthdays4(2001, 2))
    # self.assertEqual(days[0], (2001, 2, 1, 3))
    # self.assertEqual(days[-1], (2001, 2, 28, 2))
    assert days matches [(2001, 2, 1, 3), *_, (2001, 2, 28, 2)]

...

def test_itermonthdays2(self):
    for firstweekday in range(7):
        cal = calendar.Calendar(firstweekday)
        # Test the extremes, see #28253 and #26650
        for y, m in [(1, 1), (9999, 12)]:
            days = list(cal.itermonthdays2(y, m))
            # self.assertEqual(days[0][1], firstweekday)
            # self.assertEqual(days[-1][1], (firstweekday - 1) % 7)
            lastweekday = (firstweekday - 1) % 7
            assert days matches [[_, .firstweekday], *_ [_, .lastweekday]]
```

That last one required adding a new variable+assignment to be able to to use it as a constant value pattern

```python

# examples from _test_multiprocessing.py

def test_current(self):
    if self.TYPE == 'threads':
        self.skipTest('test not appropriate for {}'.format(self.TYPE))

    current = self.current_process()
    # authkey = current.authkey

    # self.assertTrue(current.is_alive())
    # self.assertTrue(not current.daemon)
    # self.assertIsInstance(authkey, bytes)
    # self.assertTrue(len(authkey) > 0)
    # self.assertEqual(current.ident, os.getpid())
    # self.assertEqual(current.exitcode, None)

    self.assertTrue(current.is_alive())
    pid = os.getpid()
    assert current matches Process(daemon=False, authkey=bytes(authkey), ident=.pid, exitcode=None) if authkey

...
def test_map_async_callbacks(self):
    call_args = self.manager.list() if self.TYPE == 'manager' else []
    self.pool.map_async(int, ['1'],
                        callback=call_args.append,
                        error_callback=call_args.append).wait()

    # self.assertEqual(1, len(call_args))
    # self.assertEqual([1], call_args[0])
    assert call_args matches [[1]]

    self.pool.map_async(int, ['a'],
                        callback=call_args.append,
                        error_callback=call_args.append).wait()
    # self.assertEqual(2, len(call_args))
    # self.assertIsInstance(call_args[1], ValueError)
    assert call_args matches [_, ValueError]
```

The first example requires again inventing a variable to use it. Also, the `is_alive()` check was left outside because its a method and not an attribute. 

```python
# examples from test_configparser.py

def test_clear(self):
    cf = self.newconfig({"foo": "Bar"})
    self.assertEqual(
        cf.get(self.default_section, "Foo"), "Bar",
        "could not locate option, expecting case-insensitive option names")
    cf['zing'] = {'option1': 'value1', 'option2': 'value2'}
    self.assertEqual(cf.sections(), ['zing'])
    # self.assertEqual(set(cf['zing'].keys()), {'option1', 'option2', 'foo'})
    assert cf matches {"zing": {"option1": _, "option2": _, "foo": _, **rest}} if not rest  # Hack to make mapping match strict 

    cf.clear()
    self.assertEqual(set(cf.sections()), set())
    # self.assertEqual(set(cf[self.default_section].keys()), {'foo'})
   assert cf[self.default_section] matches {"foo": _, **rest}} if not rest  # Hack to make mapping match strict 

```

Note that I would have been happier here with strict mapping semantics. It still looks much more readable (especially the first line)

**Comment by viridia** [comment]
It may be interesting to compare the way this is done in Jest (a popular testing framework for JavaScript):

```
expect(value).toEqual({
  letters: ['a', 'b', expect.greaterThan(3)],
  people: {
    fred: "Smith",
    john: expect.not.isNull(),
  }
})
```
Basically, you can pass in an object that has the same 'shape' as the desired result, and the individual values can either be literal values, or a matcher instance, such as `expect.isGreaterThan()`. The testing framework does a deep comparison, with a type test on each field to determine whether it should be compared via equality or by invoking the matcher.

**Comment by gvanrossum** [comment]
Hm. The syntax `assert <expr> matches <pattern>` sounds like nothing so much as COBOL, and it feels too ad-hoc.

I would prefer to close this issue as I see no value in keeping it open (I'm certainly not in favor of putting this in "Postponed ideas").
