### ISSUE TITLE
Rename 'target' to 'subject'?

### ISSUE THREAD

**Issue by gvanrossum** [gvanrossum/patma#127]
In the paper that @Tobias-Kohn just sent to a few of us, what we call the "target" of a `match` statement is called the "subject". Maybe we should switch to this terminology in the PEP? "Target" is also used in the phrase "assignment target" and I found two uses (in the text defending the choice of `_` as the wildcard symbol) where just "target" was used to mean the latter.

**Comment by viridia** [comment]
Yes, that is much better. I was hesitant about using 'target' myself, but I have been using it consistently since I didn't have a better word.

**Comment by gvanrossum** [comment]
@viridia Can you please send a PR towards the peps repo?

**Comment by viridia** [comment]
All right, I can do that.

**Comment by viridia** [comment]
https://github.com/python/peps/pull/1498

**Comment by gvanrossum** [comment]
Done.
