### ISSUE TITLE
Matched a wrong case in my testcase.

### ISSUE THREAD

**Issue by 00Kai0** [gvanrossum/patma#131]
Hi @gvanrossum . I tried with this code:
```
from dataclasses import dataclass

@dataclass
class Point:
    x: int
    y: int

z = 41

def whereis(point):
    w = 23
    match point:
        case Point(0, 0):
            print("Origin")
        case Point(0, y):
            print(f"Y={y}")
        case Point(x, 0):
            print(f"X={x}")
        case Point():
            print("Somewhere else")
        case 23:
            print("Not the answer")
        case w:
            print("Not the answer, local w")
        case z:
            print("Not the answer, local z")
        case _:
            print("other")
whereis(42)
```

It returned "Not the answer, local w".
I think it should match nothing and return "other", but it matched `w`.
The `w` had been assigned to 23, but it didn't match `23` at first. 
It confoused me.
I don't know if there is a problem with my understanding. I hope you can have a look :)

**Comment by gvanrossum** [comment]
‘case w:’ is seen by the parser as a capture pattern. Those are irrefutable (always match) and the first such is selected. You could use ‘case 23’.
