### ISSUE TITLE
Django Example in PEP

### ISSUE THREAD

**Issue by Tobias-Kohn** [gvanrossum/patma#135]
[According to Mark Shannon](https://mail.python.org/archives/list/python-dev@python.org/message/IPRBLWDE64FACRUKORC32QLHRT3NFBVI/) there are two bugs in the Django example we included in the PEP.

> Saves two lines of code, but introduces two bugs!

Indeed, I see one bug in that the `len(value) > 1` has turned into a `len(value) >= 1`.  This is probably something we might want to correct.  Unfortunately this makes the example a bit less elegant and compelling.

On the other hand, we could fold the preceding line `value = classdict[key]` directly into the match statement.
```python
match classdict[key]:
    case [v, *w, label := (Promise() | str())]:
        value = (v,) + tuple(w)
    case value:
        label = key.replace('_', ' ').title()
```
I am not sure about a second bug, though.

P. S. It saves a bit more than two lines, of course.  Why is it that everyone tends to be so pedantic when highlighting errors and shortcomings, but takes quite some liberty with accepting any benefits...?

**Comment by gvanrossum** [comment]
I suspect that Mark is writing in the style of a critical reviewer of academic papers. But I think most of his critique is due to personal preferences.

I assume the second bug in the example is that we accept other sequences. I prefer not to fix that, I assume that the original code just doesn’t care except it does want strings, and we’ve got that right.

I am not sure your fix is best, need to get to a real keyboard to compose a better one.

**Comment by Tobias-Kohn** [comment]
Well, not exactly:  Mark is primarily putting up a couple of straw men, which has nothing to do with academic reviewing (although many academic reviewers do the same, unfortunately).

And yes, I personally would have used something like a guard to say `if len(v) > 0`, but I wanted to avoid that because of possible criticism that it does not save or change anything that was not there in the first place.  As I am not really happy with the above solution, I certainly welcome if you know how to improve it.

I, too, thought that the second bug he is alluding to might be the tuple/list issue.  But like you, I just do not see this as a bug at all.

**Comment by dmoisset** [comment]
I missed the `>` vs `>=` issue when writing this example, but I was fully aware of the sequences vs list/tuple, and was happier with the new version (I think it *fixes* a bug rather than adding one). I would add `if v` as a guard, just as a simple way of saying "a non empty value"

**Comment by dmoisset** [comment]
(and if I want to avoid the guard, I'd rather use `(v, *w)` in the body mimicing the pattern above rather than the `(v,) + tuple(w)` in your example)

**Comment by brandtbucher** [comment]
Sorry I didn't see this issue and opened python/peps#1523.

**Comment by Tobias-Kohn** [comment]
@dmoisset  I agree that it rather _fixes_ a bug.  And yes, of course, the `(v, *w)` would be much better.

**Comment by gvanrossum** [comment]
Yeah, I like the solution of adding `if v` as a guard.
