### ISSUE TITLE
Literal comparision for float('inf') and float('-inf')

### ISSUE THREAD

**Issue by SaschaSchlemmer** [gvanrossum/patma#141]
At the end of https://github.com/gvanrossum/patma/issues/139 when bringing up serializing to json `float('inf')` and `float('-inf')` have been brought up (as well as `float('nan')` which is another matter altogether). Since both equality checking `float('inf') == float('inf')` and `isinstance(float('inf'), float)` return true I wonder why the following does not match (and whether it should):

```
match float('inf'):
    case float('inf'): ... # does not match
```

**Comment by gvanrossum** [comment]
I don't think there's anything to do about this, and I honestly don't think it's important.

For classes that take multiple types as arguments you can't support more than one type in general. E.g. we can't make these work either:
```
case int('42'): ...
case str(42): ...
```
These will match nothing.

**Comment by brandtbucher** [comment]
Yeah, I think the "correct" way to handle `nan`/`inf` is using guards:

```py
match f:
    case float() if math.isnan(f): ...
    case float() if math.isinf(f): ...
    case float(): ...
    case _: ...
```

Ditto for `nanj`/`infj`, if you're unlucky enough to deal with those regularly.

**Comment by dmoisset** [comment]
For documentation purposes: `case math.inf` should also work for infinities (not for `math.nan` because they don't compare with `==`), and it allows you to do a signed match (`math.isinf()` is "sign-insensitive").
