### ISSUE TITLE
Phrasing update in abstract and overview

### ISSUE THREAD

**Issue by dmoisset** [gvanrossum/patma#151]
I applied the phrasing changes suggested by the SC in the abstract section. There was nothing in the overview.

I also added a sentence reinforcing that matching includes variable capture.

There's a draft PR at python/peps#1576; It's a draft until the team approves, then I can switch it to a full-fledged PR to be merged.

**Comment by gvanrossum** [comment]
https://github.com/python/peps/pull/1573 Is also relevant.

**Comment by gvanrossum** [comment]
Sorry, I think this got superseded by python/peps#1573. Closing.
