### ISSUE TITLE
Unify the PEP 634 and implementation grammars

### ISSUE THREAD

**Issue by brandtbucher** [gvanrossum/patma#162]
We should prefer PEP 634 rule names, order, etc.

**Comment by brandtbucher** [comment]
Done. The grammar is rules are a bit different for class pattern since I couldn't find a clean way of parsing only the arguments to a call in one rule like the PEP does.

**Comment by gvanrossum** [comment]
Thanks! No worries about class pattern, it's clear that the two are equivalent, and I agree that getting the actions right for the version in the PEP would be a tad complicated. Maybe we should just change the PEP grammar? It's the same number of lines.
