### ISSUE TITLE
work error with zip param "strict=False" on py386

### ISSUE THREAD

**Issue by leonjwfrank** [gvanrossum/patma#171]
Hi, Gvanrossum
when  I am try running the class pattern, util case checks call function pat.translate("X")
there had an error at line 362 on module:  patma.py

            for pat, field in zip(self.posargs, self.fields, strict=False):  # py 3.8.6  can not support this params strict

when I try to remove the params strict, it was work again.

I am thinking about this problem to report, maybe have some help for your work.

thanks a lot.
Franklin

**Comment by gvanrossum** [comment]
That’s an old I support bit of code anyway.
