### ISSUE TITLE
Meta: next steps

### ISSUE THREAD

**Issue by viridia** [gvanrossum/patma#42]
I'd like to talk about what are the next steps towards getting this PEP adopted.

Here's the current status as I see it:

* Most of the major issues have converged to a consensus. There are a few remaining bikeshed issues outstanding.
* Work has begun on a reference implementation.

Here's some things that need to happen, in no particular order:

* A few issues are not yet labeled. I have labeled as "open" the ones that do not appear to have come to a conclusion. We should label the remaining ones.
* Get all of the remaining "open" issues into a resolved (accepted, rejected, postponed) state. Label as appropriate. (Hmmm: https://github.com/apps/polls)
* Finish the reference implementation.
* Post the PEP proposal to a wider audience.
  * Guido mentioned to me that he doesn't want to open up this discussion until after 3.9 is in the can, due to the potential distraction that would likely result.
* Get an officially assigned PEP number for this.
* Gather public feedback and evangelize.
* Get steering council approval
* Create or gather more code examples using the new feature.
* Write Sphinx docs for the Python language manual (that is something I can help out with, but it seems premature to work on it until after the PEP has been ratified).

Anything missing from that list?

**Comment by gvanrossum** [comment]
This issue has outlived its usefulness. The rest of the process is just following PEP 1.
