### ISSUE TITLE
Current implementations of switch-like behavior

### ISSUE THREAD

**Issue by bskinn** [gvanrossum/patma#87]
There are at least two PyPI packages I know of that were created to implement a switch-like behavior (not nearly as extensive as the match-case behavior of the PEP):

- [`switchcase`](https://pypi.org/project/switchcase/)
- [`switchlang`](https://pypi.org/project/switchlang/)

Would these be suitable for an 'existing art' section of the PEP?

I would think there are others, as well.

**Comment by natelust** [comment]
This is not meant to be a toot my own horn kind of comment, so please don't take it as such. Is it also worth adding the mail and GitHub repo I sent out to python ideas the other day with a very similar proposal? That way it highlights that although similar this is distinct and not a continuation of that chain.

**Comment by bskinn** [comment]
My apologies to creators of any other prior art that I've not mentioned -- I didn't mean to imply that these are the only ones that should be included, they're just the ones I know of. (I haven't been following the python-ideas discussion.)

**Comment by natelust** [comment]
No offense take!  I really was not trying to make it a "what about me" comment, I'm sorry if came across that way. It just so happens this group and I have been working on very similar proposals at the same time without knowing. I just wanted to help highlight the difference.

**Comment by brandtbucher** [comment]
Eh, I'm not sure we need it. This PEP is already ~9,000 words long, and there are dozens and dozens of pattern-matching and switch-case libraries available.

If we do decide that including a study of prior art is necessary, @gvanrossum compiled a list of the most popular languages, Python packages, and mailing list threads a few months ago when we were in the very early stages of the proposal.

**Comment by bskinn** [comment]
Ahhh, I didn't realize the prior art was that extensive! Makes sense - thanks!
