### ISSUE TITLE
Solving Scoping Issues: Avoiding Undefined Behaviors

### ISSUE THREAD

**Issue by thautwarm** [gvanrossum/patma#96]
So far in the PEP, some program behavior about name pattern is not yet specified.
    
Say, what's the output of the following program?

```python
a =  1
match [10, 20]:
    case [a, 2]:
        ...
    case _:
        print(a) # 1 or 10?
```

@gvanrossum has commented "the behavior is undefined".

The reference languages like Scala, Rust, F#, all of them implemented local name shadowing,
so that the body of `case _` is expected to print 1.

The explanation for this semantics is more straightforward than being a UB: if a case not matched,
we just treat the whole of this case failed, and `a` will be not be bound unexpectedly.

This can be implemented by
1. generating a unique name for a name pattern `a`,
2. keeping the mapping relationship statically in the compiler, and
3. actually binding the names once the current `case ...` succeeded.

--------------------------------------

For above exemplar code,

```python
a =  1
match [10, 20]:
    case [a, 2]:
        ...
    case _:
        print(a) # 1 or 10?
```

is translated as 

```python
a =  1
match [10, 20]:
    case [<xxx>, 2]:
        a = <xxx>
        ...
    case _:
        print(a) # 1 or 10?
```

`<xxx>` here indicates a generated unique name that cannot be written down by users.

The compiler knows `<xxx>` will be bound to `a` if `case [a, 2]` succeeded.

**Comment by brandtbucher** [comment]
We don't agree that there are issues to be solved here. The behavior is intentional, and is consistent with Python's scoping rules for similar constructs:

```py
>>> x = "spam"
>>> if (x := "eggs") and False:
...     ...
... 
>>> x
'eggs'
```

It's specifically undefined so as to allow the compiler the flexibility to break the matching logic early (for example, if the length of a sequence or mapping pattern is incompatible with the value of the target). What's more, it even lets us define the behavior later, if there is an overwhelming justification for doing so.

**Comment by thautwarm** [comment]
People might not ware a variable binding occurred even the a case failed, because usually **they don't aware your implementation**.

They would simply regard the pattern as a whole, and feel strange when they found a variable modified by an unmatched case.

When it becomes to `if` statements, things become clean. One can know the details of the execution. 

`if` is not an abstract thing, while `match` is.

**Comment by thautwarm** [comment]
They know pattern matching performed from left to right, so it's the execution of `__match__` and `__eq__`, but other details not specified.

For someone understanding the implementation, like you, will naturally think this is consistent because the code gets lowered into equivalent `if-else` statements or bytecode instructions.

But for common users, they do not know the implementation of pattern matching, they don't know how the name bindings are treated. They just know a name pattern will bind a name, and they write down `case C(a, ...)` and this case failed, they ask, "why this failed but `a` modified?"

**Comment by Tobias-Kohn** [comment]
@thautwarm  In contrast to all those other languages, Python has extensive reflection capabilities.  It is easy enough to access local variables (e.g. through `locals()`) and this is a feature that is effectively in use.  With what you are proposing here, it will become very difficult to predict where that variable and its value has ended up.  Python is all about _not_ doing compiler magic, but being very predictable (und thus understandable!).  We should stick to that.

The only way to have what you are proposing is by introducing yet another scope with its own local variables.  This means, in effect, that each case clause would be executed with its own frame just like a function or class definition.  This, in turn affects what `return` means, for instance.  But it also means that the following will no longer work:
```python
def foo(x):
    shape = '?'
    match x:
        case Point():
            shape = 'point'
        case Line():
            shape = 'line'
    print(shape)
```
Each case clause now has its own local variable `shape` shadowing the local variable of `foo`.  So, you need to use `nonlocal` to work around that.

Apart from what @brandtbucher has already said (and with which I fully agree), introducing such local scopes for name binding introduces a whole lot of difficulties and issues.  I am afraid this will simply not work in Python.

**Comment by thautwarm** [comment]
> With what you are proposing here, it will become very difficult to predict where that variable and its value has ended up.

You don't have to actually delete the generated variables.

If you think `locals` access unexpected variables, you can delete them after binding the user written variables   with them. 

Also, how do you feel about the name`.0` generated in comprehemsions and `except E as e: x = e`? Predicting them can be guarantee but still need special knowledge.

Predicting names in very rare cases might be difficult,  but >80%(I doubt even > 99.9%) cases, names are well predictable with the traditional technique called Name Shadowing, which is not a compiler magic.

> This means, in effect, that each case clause would be executed with its own frame just like a function or class definition.

Python has no immediately invoked functions, so no.

> introducing such local scopes for name binding introduces a whole lot of difficulties and issues

I cannot say it's very easy but quite far from "difficulty".

And the only issue is the generated names maybe accessed by `locals`, however these names are not valid identifier, and users can safely skip them. As PEP 622 is new, no breakage will be produced.

Example generation: https://gist.github.com/thautwarm/b69c39fdfb47cc32727cae5287a90768

My implementation is nearly full featured. https://github.com/thautwarm/moshmosh#case-study--pattern-matching

----
I want to stress a fact: taking no actions to this will increase the mental burden of Python users. They don't understand the underlying impl of pattern matching, don't expect they can intentionally notice the change of a name bound by name patterns, it's complex to people from many fields. They just make some words making Python lovers upset.

**Comment by thautwarm** [comment]
Implementation for this: visit all name patterns in a case clause, build a map from actual name to generated names. When a name pattern binding a name, lookup the generated name. Do this for guard ecoressions as well.

When the case succeeded, bind the generated names to the actual names, and delete all generated names.

**Comment by louy2** [comment]
Suppose I have a function `isFirst(arr, x)`, and I'd like to log the value of `x` in the default branch in a debugging session:

```py
def isFirst(arr, x):
    result = false
    match arr:
        case [x, _]:
            result = true
            print('{x} is the first')
        case _:
            result = false
            print('{x} is not the first')
    return result
```

Are you telling me that if I run the function, I might see the following?

```py
>>> isFirst([3, 2], 3)
3 is the first
true
>>> isFirst([3, 2], 1)
3 is not the first
false
```

**Comment by thautwarm** [comment]
@louy2 could you please see #90 .

At the first glance, I used to think it a good example, but after I read your semantics, unfortunately no..

**Comment by gvanrossum** [comment]
Enough already.
